## Logistic Regression Modeling for Early Stage Diabetes Risk Prediction

## Part 2.1: Getting familiar with linear algebraic functions

#### Tasks
- Create matrix of size 10*10 with random integer numbers
- Compute the following linear algebric operations on the matrix using built in functions supported in Numpy, Scipy etc.
  - Find inverse of the matrix and print it
  - Calculate dot product of the matrix with same matrix in transpose A.AT
  - Decompose the original matrix using eigen decomposition print the eigen values and eigen vectors
  - Calculate jacobian matrix 
  - Calculate hessian matrix

In [332]:
import numpy as np
import numpy.linalg as npa
import numdifftools as nd

In [333]:
m = np.random.rand(10,10)

In [334]:
m_inv = npa.inv(m)
m_inv

array([[-0.80772092,  0.30260031,  0.39155471, -1.78538872, -1.10370659,
         0.59872608, -0.38170656,  0.23072012,  1.37402952,  0.17644944],
       [ 0.67742376, -0.51788048, -0.95096551,  1.31567213, -0.18551959,
        -0.25707236, -0.47887062, -1.05806079,  1.31247957,  0.76803523],
       [ 0.86423699, -0.64272325, -0.39575715,  1.26623465,  0.24494028,
        -0.63271606,  0.59347883, -0.96193673,  0.93449075, -0.24461815],
       [-1.14957835,  0.07206969,  1.41089826, -1.00993666,  1.13918711,
        -1.03760676, -0.80431227,  3.43108504, -3.28485073,  0.29811406],
       [-2.7386576 ,  0.14321873,  1.70737487, -3.45650899, -0.70833339,
         2.40955302,  1.14238617,  3.05604817, -2.78991546, -0.25351041],
       [ 2.02045309,  0.26163395, -0.55930917,  3.17332227,  0.00485749,
        -0.21320802,  0.23994083, -3.47063222,  1.32473137, -0.12390651],
       [ 1.56676686, -0.22715426, -0.72857439,  0.35212509,  0.12296447,
         0.38143279,  0.23626817, -2.44744578

In [335]:
np.dot(m, m.T)

array([[5.15667616, 2.94585992, 2.7862475 , 1.61391818, 2.26104627,
        3.91355549, 1.98659682, 5.24494633, 3.51118382, 3.3133095 ],
       [2.94585992, 2.78946485, 1.634641  , 1.19648629, 1.51014549,
        2.25692603, 1.68596389, 3.48490359, 2.50722112, 2.02449552],
       [2.7862475 , 1.634641  , 3.08911423, 1.57137393, 1.67911363,
        2.35207665, 1.32424329, 3.47581768, 2.9587759 , 1.8134395 ],
       [1.61391818, 1.19648629, 1.57137393, 1.26356742, 1.26260084,
        1.79693094, 0.92532622, 2.44001542, 1.96729782, 1.26150998],
       [2.26104627, 1.51014549, 1.67911363, 1.26260084, 2.42408912,
        2.54053972, 1.08804187, 3.14443254, 2.62862841, 1.48587814],
       [3.91355549, 2.25692603, 2.35207665, 1.79693094, 2.54053972,
        3.93169996, 1.29460055, 4.54872393, 3.26764711, 2.62284206],
       [1.98659682, 1.68596389, 1.32424329, 0.92532622, 1.08804187,
        1.29460055, 2.05490138, 2.68637461, 2.04657219, 1.70279783],
       [5.24494633, 3.48490359, 3.4758176

In [336]:
#eigen value and vector
w, v = npa.eig(m)
w, v

(array([ 4.98338811+0.j        ,  0.38973775+0.26045805j,
         0.38973775-0.26045805j,  0.10108665+0.62177519j,
         0.10108665-0.62177519j, -0.07193551+0.37964314j,
        -0.07193551-0.37964314j, -0.51057664+0.32377085j,
        -0.51057664-0.32377085j, -0.94204415+0.j        ]),
 array([[-0.36968667+0.j        , -0.28116214+0.10631745j,
         -0.28116214-0.10631745j,  0.06881063-0.39858691j,
          0.06881063+0.39858691j,  0.43007413+0.14445737j,
          0.43007413-0.14445737j, -0.27490474-0.08512556j,
         -0.27490474+0.08512556j,  0.01493106+0.j        ],
        [-0.30563113+0.j        ,  0.06712817+0.29239713j,
          0.06712817-0.29239713j, -0.17044362-0.18162464j,
         -0.17044362+0.18162464j,  0.11558963-0.2325493j ,
          0.11558963+0.2325493j , -0.14998371+0.25956991j,
         -0.14998371-0.25956991j,  0.52245275+0.j        ],
        [-0.26175657+0.j        ,  0.01655073-0.20276268j,
          0.01655073+0.20276268j, -0.22850178+0.26669055j

In [337]:
#Jacobian Matrix
func = lambda x : x**3
nd.Jacobian(func)(m)

array([[[1.24534997e+00, 1.33938821e+00, 1.03967835e-01, 2.72191646e+00,
         2.81646402e+00, 5.89997629e-01, 2.76265645e+00, 4.55160763e-02,
         2.11866845e+00, 1.72610337e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.0

In [338]:
def rosen(x): return (1-x[0])**2 + 105.*(x[1]-x[0]**2)**2
nd.Hessian(rosen)(m[1])

array([[ 453.98849416, -258.61596842,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [-258.61596842,  210.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.        ,    0.        ,    0.        ,    0

## Part 2.2: Logistic Regression using newton method

### Logistic regression
Logistic regression uses an equation as the representation, very much like linear regression.

Input values (x) are combined linearly using weights or coefficient values (referred to as W) to predict an output value (y). A key difference from linear regression is that the output value being modeled is a binary values (0 or 1) rather than a continuous value.<br>

###  $\hat{y}(w, x) = \frac{1}{1+exp^{-(w_0 + w_1 * x_1 + ... + w_p * x_p)}}$

#### Dataset
The dataset is available at <strong>"data/diabetes_data.csv"</strong> in the respective challenge's repo.<br>
<strong>Original Source:</strong> http://archive.ics.uci.edu/ml/machine-learning-databases/00529/diabetes_data_upload.csv. The dataset just got released in July 2020.<br><br>

#### Features (X)

1. Age                - Values ranging from 16-90
2. Gender             - Binary value (Male/Female)
3. Polyuria           - Binary value (Yes/No)
4. Polydipsia         - Binary value (Yes/No)
5. sudden weight loss - Binary value (Yes/No)
6. weakness           - Binary value (Yes/No)
7. Polyphagia         - Binary value (Yes/No)
8. Genital thrush     - Binary value (Yes/No)
9. visual blurring    - Binary value (Yes/No)
10. Itching           - Binary value (Yes/No)
11. Irritability      - Binary value (Yes/No)
12. delayed healing   - Binary value (Yes/No)
13. partial paresis   - Binary value (Yes/No)
14. muscle stiffness  - Binary value (Yes/No)
15. Alopecia          - Binary value (Yes/No)
16. Obesity           - Binary value (Yes/No)

#### Output/Target target (Y) 
17. class - Binary class (Positive/Negative)

#### Objective
To learn logistic regression and practice handling of both numerical and categorical features

#### Tasks
- Download, load the data and print first 5 and last 5 rows
- Transform categorical features into numerical features. Use label encoding or any other suitable preprocessing technique
- Since the age feature is in larger range, age column can be normalized into smaller scale (like 0 to 1) using different methods such as scaling, standardizing or any other suitable preprocessing technique (Example - sklearn.preprocessing.MinMaxScaler class)
- Define X matrix (independent features) and y vector (target feature)
- Split the dataset into 60% for training and rest 40% for testing (sklearn.model_selection.train_test_split function)
- Train Logistic Regression Model on the training set (sklearn.linear_model.LogisticRegression class)
- Use the trained model to predict on testing set
- Print 'Accuracy' obtained on the testing dataset i.e. (sklearn.metrics.accuracy_score function)

#### Further fun (will not be evaluated)
- Plot loss curve (Loss vs number of iterations)
- Preprocess data with different feature scaling methods (i.e. scaling, normalization, standardization, etc) and observe accuracies on both X_train and X_test
- Training model on different train-test splits such as 60-40, 50-50, 70-30, 80-20, 90-10, 95-5 etc. and observe accuracies on both X_train and X_test
- Shuffling of training samples with different *random seed values* in the train_test_split function. Check the model error for the testing data for each setup.
- Print other classification metrics such as:
    - classification report (sklearn.metrics.classification_report),
    - confusion matrix (sklearn.metrics.confusion_matrix),
    - precision, recall and f1 scores (sklearn.metrics.precision_recall_fscore_support)

#### Helpful links
- Scikit-learn documentation for logistic regression: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
- How Logistic Regression works: https://machinelearningmastery.com/logistic-regression-for-machine-learning/
- Feature Scaling: https://scikit-learn.org/stable/modules/preprocessing.html
- Training testing splitting: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
- Classification metrics in sklearn: https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics
- Use slack for doubts: https://join.slack.com/t/deepconnectai/shared_invite/zt-givlfnf6-~cn3SQ43k0BGDrG9_YOn4g

In [339]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [340]:
# Download the dataset from the source


In [341]:
# NOTE: DO NOT CHANGE THE VARIABLE NAME(S) IN THIS CELL
# Load the data
data = pd.read_csv('data/diabetes_data.csv')

In [342]:
data.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0   40   Male       No        Yes                 No      Yes         No   
1   58   Male       No         No                 No      Yes         No   
2   41   Male      Yes         No                 No      Yes        Yes   
3   45   Male       No         No                Yes      Yes        Yes   
4   60   Male      Yes        Yes                Yes      Yes        Yes   

  Genital thrush visual blurring Itching Irritability delayed healing  \
0             No              No     Yes           No             Yes   
1             No             Yes      No           No              No   
2             No              No     Yes           No             Yes   
3            Yes              No     Yes           No             Yes   
4             No             Yes     Yes          Yes             Yes   

  partial paresis muscle stiffness Alopecia Obesity     class  
0              No              Yes      Yes     Yes  Positive  
1             Yes               No      Yes      No  Positive  
2              No              Yes      Yes      No  Positive  
3              No               No       No      No  Positive  
4             Yes              Yes      Yes     Yes  Positive

In [343]:
data.columns

Index(['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss',
       'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring',
       'Itching', 'Irritability', 'delayed healing', 'partial paresis',
       'muscle stiffness', 'Alopecia', 'Obesity', 'class'],
      dtype='object')

In [344]:
# Handle categorical/binary columns

In [345]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [346]:
for name in data.columns:
    if(name != 'Age'):
        data[name] = encoder.fit_transform(data[name])
data.head()

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0   40       1         0           1                   0         1   
1   58       1         0           0                   0         1   
2   41       1         1           0                   0         1   
3   45       1         0           0                   1         1   
4   60       1         1           1                   1         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

In [347]:
# Normalize the age feature

In [348]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
age_norm = scaler.fit_transform(pd.DataFrame(data.Age))
data.Age = age_norm
data.insert(0, "Atr0", [1]*len(data), allow_duplicates=True)
data.head()

Atr0       Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0     1  0.324324       1         0           1                   0         1   
1     1  0.567568       1         0           0                   0         1   
2     1  0.337838       1         1           0                   0         1   
3     1  0.391892       1         0           0                   1         1   
4     1  0.594595       1         1           1                   1         1   

   Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0           0               0                0        1             0   
1           0               0                1        0             0   
2           1               0                0        1             0   
3           1               1                0        1             0   
4           1               0                1        1             1   

   delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                1                0                 1         1        1   
1                0                1                 0         1        0   
2                1                0                 1         1        0   
3                1                0                 0         0        0   
4                1                1                 1         1        1   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

In [349]:
# Define your X and y
X = data.loc[:, data.columns != 'class'].values
y = np.array(data['class'])

In [350]:
# Split the dataset into training and testing here
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

In [448]:
def predict(X, weights):
    '''Predict class for X.
    For the given dataset, predicted vector has only values 0/1
    Args:
        X : Numpy array (num_samples, num_features)
        weights : Model weights for logistic regression
    Returns:
        Binary predictions : (num_samples,)
    '''

    ### START CODE HERE ###
    z = X@weights
    logits = sigmoid(z)
    y_pred = logits.round()
    ### END CODE HERE ###
    
    return y_pred

In [352]:
def sigmoid(z):
        '''Sigmoid function: f:R->(0,1)
        Args:
            z : A numpy array (num_samples,)
        Returns:
            A numpy array where sigmoid function applied to every element
        '''
        ### START CODE HERE
        sig_z = 1/(1 + np.exp(-z))
        ### END CODE HERE
        
        assert (z.shape==sig_z.shape), 'Error in sigmoid implementation. Check carefully'
        return sig_z

In [353]:
def cross_entropy_loss(y_true, y_pred):
    '''Calculate cross entropy loss
    Note: Cross entropy is defined for multiple classes/labels as well
    but for this dataset we only need binary cross entropy loss
    Args:
        y_true : Numpy array of true values (0/1) of size (num_samples,)
        y_pred : Numpy array of predicted values (probabilites) of size (num_samples,)
    Returns:
        Cross entropy loss: A scalar value
    '''
    # Fix 0 values in y_pred
    y_pred = np.maximum(np.full(y_pred.shape, 1e-7), np.minimum(np.full(y_pred.shape, 1-1e-7), y_pred))
    
    ### START CODE HERE
    ce_loss = np.sum(-y_true*np.log(y_pred) - (1-y_true)*np.log(1-y_pred))
    ### END CODE HERE
    
    return ce_loss

In [450]:
def newton_optimization(X, y, max_iterations=25):
    '''Implement netwon method for optimizing weights
    Args:
        X : Numpy array (num_samples, num_features)
        max_iterations : Max iterations to update the weights
    Returns:
        Optimal weights (num_features,)
    '''
    num_samples = X.shape[0]
    num_features = X.shape[1]
    # Initialize random weights
    weights = np.random.random(num_features,)
    # Initialize losses
    losses = []
    
    # Newton Method
    for i in range(max_iterations):
        # Predict/Calculate probabilties using sigmoid function
        y_p = sigmoid(X@weights)
        #cost function
        #cost = lambda x : (1/num_samples) * np.sum(-y*np.log(y_p) - (1-y)*np.log(1-y_p))
        # Define gradient for J (cost function) i.e. cross entropy loss
        #gradient = 1/num_samples * np.sum(X.T@(y_p - y)).T
        
        #gradient = nd.Jacobian(cost)(X)
        gradient = 1/num_samples *(X.T @ (y_p - y))
        # Define hessian matrix for cross entropy loss
        #hessian = 1/num_samples * np.sum((y_p*(1-y_p))*(X.T@X))
        hessian= (1/num_samples)*X.T.dot(np.diag(y_p)).dot(np.diag(1-y_p)).dot(X)
        # Update the model using hessian matrix and gradient computed
        weights = weights - npa.inv(hessian)@gradient
        
        # Calculate cross entropy loss
        loss = cross_entropy_loss(y, y_p)
        print('loss:',loss)
        # Append it
        losses.append(loss)

    return weights, losses

In [451]:
# Train weights
weights, losses = newton_optimization(X_train, y_train)

loss: 355.8675950380468
loss: 941.6030163166164
loss: 2947.4704712426533


<ipython-input-352-f6312c3c8862>:9: RuntimeWarning: overflow encountered in exp
  sig_z = 1/(1 + np.exp(-z))


LinAlgError: Singular matrix

In [ ]:
 exp = np.zeros((num_features, num_features))
        for i in range(num_samples):
            exp += (y_p[i]*(1-y_p[i]))*(X[i,:].T@X[i,:])
        hessian = (1/num_samples) * exp

In [ ]:
# Plot the loss curve
plt.plot([i+1 for i in range(len(losses))], losses)
plt.title("Loss curve")
plt.xlabel("Iteration num")
plt.ylabel("Cross entropy curve")
plt.show()

In [ ]:
our_model_test_acuracy = accuracy_score(y_test, predict(X_test, weights))

print(f"\nAccuracy in testing set by our model: {our_model_test_acuracy}")

#### Compare with the scikit learn implementation

In [435]:
# Initialize the model
model = LogisticRegression(solver='newton-cg', verbose=1)

In [436]:
# Fit the model. Wait! We will complete this step for you ;)
model.fit(X_train, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished


LogisticRegression(solver='newton-cg', verbose=1)

In [437]:
# Predict on testing set X_test
y_pred = model.predict(X_test)

In [438]:
# Print Accuracy on testing set
sklearn_test_accuracy = accuracy_score(y_test, y_pred)

print(f"\nAccuracy in testing set by sklearn model: {sklearn_test_accuracy}")


Accuracy in testing set by sklearn model: 0.9182692307692307
